/**
 * Native Firebase + Google Sign-In bootstrap for the mobile app.
 *
 * - Uses @react-native-firebase/auth for real native phone OTP (no reCAPTCHA needed).
 * - Uses @react-native-google-signin/google-signin for the native Google sheet.
 * - Firebase project config is taken from android/app/google-services.json (auto-loaded
 *   by the Google Services Gradle plugin), so nothing to hardcode here for Firebase
 *   itself. Only the Google web client ID is configured here for ID-token exchange.
 *
 * Project: genelink-1plh2
 * Web client ID below is auto-generated by Firebase when Google sign-in is enabled
 * and is found in Firebase Console -> Authentication -> Sign-in method -> Google
 * (or Google Cloud Console -> APIs & Services -> Credentials -> "Web client (auto created by Google Service)").
 */

import auth, { type FirebaseAuthTypes } from "@react-native-firebase/auth";
import {
  GoogleSignin,
  statusCodes,
} from "@react-native-google-signin/google-signin";

/**
 * Firebase project metadata (public values — same as web's NEXT_PUBLIC_FIREBASE_*).
 * Kept here for reference / debugging only. The native SDK reads its config from
 * google-services.json, so changing these values has no runtime effect.
 */
export const FIREBASE_PROJECT = {
  apiKey: "AIzaSyB65qKcK6eDQUdD8tRPC1dUKJqZBU7wSnk",
  authDomain: "genelink-1plh2.firebaseapp.com",
  projectId: "genelink-1plh2",
  storageBucket: "genelink-1plh2.firebasestorage.app",
  messagingSenderId: "181049207912",
  appId: "1:181049207912:web:84693b62a1fe7dc3925fdd",
} as const;

/**
 * Web OAuth client ID auto-created by Firebase for Google sign-in.
 * Found in Firebase Console -> Project settings -> Cloud Messaging /
 * Authentication tab, OR in Google Cloud Console -> APIs & Services -> Credentials
 * (the entry titled "Web client (auto created by Google Service)").
 *
 * Format: <NUMERIC_PROJECT>-<HASH>.apps.googleusercontent.com
 *
 * REPLACE the placeholder below with the real value from your Firebase project,
 * then run `npm run prebuild` once. The string is public (it's embedded in the
 * web bundle anyway), so it is safe to commit.
 */
export const GOOGLE_WEB_CLIENT_ID =
  "REPLACE_WITH_FIREBASE_AUTO_GOOGLE_WEB_CLIENT_ID.apps.googleusercontent.com";

let googleConfigured = false;

export function configureGoogleSignIn(): void {
  if (googleConfigured) return;
  GoogleSignin.configure({
    webClientId: GOOGLE_WEB_CLIENT_ID,
    offlineAccess: false,
  });
  googleConfigured = true;
}

export { auth, statusCodes, GoogleSignin };
export type { FirebaseAuthTypes };
